require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

  describe PatientHistoriesController do

  # This should return the minimal set of attributes required to create a valid
  # PatientHistory. As you add validations to PatientHistory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "alcohol" => "false" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PatientHistoriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all patient_histories as @patient_histories" do
      patient_history = PatientHistory.create! valid_attributes
      get :index, {}, valid_session
      assigns(:patient_histories).should eq([patient_history])
    end
  end

  describe "GET show" do
    it "assigns the requested patient_history as @patient_history" do
      patient_history = PatientHistory.create! valid_attributes
      get :show, {:id => patient_history.to_param}, valid_session
      assigns(:patient_history).should eq(patient_history)
    end
  end

  describe "GET new" do
    it "assigns a new patient_history as @patient_history" do
      get :new, {}, valid_session
      assigns(:patient_history).should be_a_new(PatientHistory)
    end
  end

  describe "GET edit" do
    it "assigns the requested patient_history as @patient_history" do
      patient_history = PatientHistory.create! valid_attributes
      get :edit, {:id => patient_history.to_param}, valid_session
      assigns(:patient_history).should eq(patient_history)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PatientHistory" do
        expect {
          post :create, {:patient_history => valid_attributes}, valid_session
        }.to change(PatientHistory, :count).by(1)
      end

      it "assigns a newly created patient_history as @patient_history" do
        post :create, {:patient_history => valid_attributes}, valid_session
        assigns(:patient_history).should be_a(PatientHistory)
        assigns(:patient_history).should be_persisted
      end

      it "redirects to the created patient_history" do
        post :create, {:patient_history => valid_attributes}, valid_session
        response.should redirect_to(PatientHistory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved patient_history as @patient_history" do
        # Trigger the behavior that occurs when invalid params are submitted
        PatientHistory.any_instance.stub(:save).and_return(false)
        post :create, {:patient_history => { "alcohol" => "invalid value" }}, valid_session
        assigns(:patient_history).should be_a_new(PatientHistory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PatientHistory.any_instance.stub(:save).and_return(false)
        post :create, {:patient_history => { "alcohol" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested patient_history" do
        patient_history = PatientHistory.create! valid_attributes
        # Assuming there are no other patient_histories in the database, this
        # specifies that the PatientHistory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PatientHistory.any_instance.should_receive(:update).with({ "alcohol" => "false" })
        put :update, {:id => patient_history.to_param, :patient_history => { "alcohol" => "false" }}, valid_session
      end

      it "assigns the requested patient_history as @patient_history" do
        patient_history = PatientHistory.create! valid_attributes
        put :update, {:id => patient_history.to_param, :patient_history => valid_attributes}, valid_session
        assigns(:patient_history).should eq(patient_history)
      end

      it "redirects to the patient_history" do
        patient_history = PatientHistory.create! valid_attributes
        put :update, {:id => patient_history.to_param, :patient_history => valid_attributes}, valid_session
        response.should redirect_to(patient_history)
      end
    end

    describe "with invalid params" do
      it "assigns the patient_history as @patient_history" do
        patient_history = PatientHistory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PatientHistory.any_instance.stub(:save).and_return(false)
        put :update, {:id => patient_history.to_param, :patient_history => { "alcohol" => "invalid value" }}, valid_session
        assigns(:patient_history).should eq(patient_history)
      end

      it "re-renders the 'edit' template" do
        patient_history = PatientHistory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PatientHistory.any_instance.stub(:save).and_return(false)
        put :update, {:id => patient_history.to_param, :patient_history => { "alcohol" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested patient_history" do
      patient_history = PatientHistory.create! valid_attributes
      expect {
        delete :destroy, {:id => patient_history.to_param}, valid_session
      }.to change(PatientHistory, :count).by(-1)
    end

    it "redirects to the patient_histories list" do
      patient_history = PatientHistory.create! valid_attributes
      delete :destroy, {:id => patient_history.to_param}, valid_session
      response.should redirect_to(patient_histories_url)
    end
  end

end
